add day01 ex02
homemade-42/ktnltr-piscine-c pull request #5
Opened 2024-01-17 15:39 UTC by ktnltr

2024-01-17 17:35 UTC, 0xChqrles requested changes
NORME

2024-01-25 15:24 UTC, 0xChqrles requested changes
fix comments

2024-01-25 15:24 UTC, 0xChqrles commented on C01/ft_ft.c
Duplicated file, please remove

2024-01-25 15:29 UTC, ktnltr commented on C01/ft_ft.c
done

2024-01-25 15:32 UTC, 0xChqrles approved these changes
lgtm

2024-01-25 15:32 UTC, merged